version: "3"
services:
  react:
    build:
      context: ../
      dockerfile: ./docker/react/Dockerfile
    image: um-rdk-basic-react
    container_name: um-rdk-basic-react
    command: yarn start
    volumes:
      - ../react/:/app
    ports:
      - "8000:3000"
